## Numpy Array 

In [1]:
import numpy as np

## Check Directory for Numpy

In [2]:
# print(dir(np))

In [3]:
# square root of any number

np.sqrt(12)

3.4641016151377544

In [4]:
np.sqrt(100)

10.0

In [5]:
np.sqrt(1245)

35.2845575287547

In [6]:
# Maximum number 

# Minimum Number

In [7]:
print("Maximum: ", np.max([1,2,3,4,5]))

print("Minimum: ",np.min([1,2,3,4,5]))

Maximum:  5
Minimum:  1


In [8]:
# Rounding off the numbers

np.ceil(25.4)

26.0

In [9]:
np.floor(25.4)

25.0

In [10]:
np.ceil(np.sqrt(121.4))

12.0

## Similarly there are many functions, can be explored for knowledge purpose. But, in Data Science limited functions are used.

In [11]:
# Convert a list into an array

In [12]:
np.array([1,2,3,4,5])

array([1, 2, 3, 4, 5])

In [13]:
type([1,2,3,4,5])

list

In [14]:
array1 = np.array([1,2,3,4,5])

type(array1)

numpy.ndarray

In [15]:
# Two Dimensional Array

In [16]:
array2 = np.array([[1,2],[3,4],[5,6]])

print('Type: ',array2.dtype)

print('\n', "*" * 20)

print('\n', array2)

Type:  int32

 ********************

 [[1 2]
 [3 4]
 [5 6]]


## If there are 2 square braces, then it is 2-D array.

In [17]:
# DataType Conversion

np.array([1,2,3,4,5], dtype=float)

array([1., 2., 3., 4., 5.])

In [18]:
# convert a list into array

a = [1,2,3,4]

array3 = np.array(a)

print(array3)

[1 2 3 4]


In [19]:
type(array3)

numpy.ndarray

In [20]:
# Copy array into other

array4 = np.asarray(array3)

type(array4)

numpy.ndarray

In [21]:
# creating matrix

matrix1 = np.array([[1,2,3],[4,5,6],[7,8,9]])

print("Type of the Matrix: ",type(matrix1))

print("Here is the Matrix: ",'\n',matrix1)

print('Dimension of the matrix: ',matrix1.ndim)

print('Size of the matrix: ',matrix1.size)

print('Shape of the matrix: ',matrix1.shape)

print('DataType of the matrix: ',matrix1.dtype)

Type of the Matrix:  <class 'numpy.ndarray'>
Here is the Matrix:  
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Dimension of the matrix:  2
Size of the matrix:  9
Shape of the matrix:  (3, 3)
DataType of the matrix:  int32


## arange and linspace

In [22]:
# range function in python

list(range(1,10))

[1, 2, 3, 4, 5, 6, 7, 8, 9]

In [23]:
# range function does not work with float

In [24]:
# range function in numpy

range1 = np.arange(1,5)

range1

array([1, 2, 3, 4])

In [25]:
range2 = np.arange(1.5,5.5)

range2

array([1.5, 2.5, 3.5, 4.5])

In [26]:
# range with step size

range3 = np.arange(2,12,2.5)

range3

# here 2.5 is step size

array([2. , 4.5, 7. , 9.5])

In [27]:
# in reverse order

range4 = np.arange(5,-6,-1)

range4

array([ 5,  4,  3,  2,  1,  0, -1, -2, -3, -4, -5])

In [28]:
# linspace

# linspace means linearly spaced or equally spaced

# in linspace last element is the elements we want to create not step size


linspace1 = np.linspace(1,10,3)

linspace1

array([ 1. ,  5.5, 10. ])

In [29]:
linspace2 = np.linspace(10,40,5)

linspace2

array([10. , 17.5, 25. , 32.5, 40. ])

In [30]:
# we can ignore endpoint to print by using following command --

linspace3 = np.linspace(10,20,num=4,endpoint=False,retstep=True)

linspace3

(array([10. , 12.5, 15. , 17.5]), 2.5)

## Matrix Creation

In [31]:
# Vectors as it will create a single row

print("Vectors ----")

print(np.zeros(3))

Vectors ----
[0. 0. 0.]


In [32]:
# Matrix (as it will create rows and columns)

print('Matrix ----')

print(np.zeros((3,3)))

Matrix ----
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [33]:
print(np.ones((4,4)))

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [34]:
print(np.zeros((4,6)))

[[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]


In [35]:
print(np.ones((3,6)))

[[1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]]


In [36]:
print(10 * np.ones((3,5)))

[[10. 10. 10. 10. 10.]
 [10. 10. 10. 10. 10.]
 [10. 10. 10. 10. 10.]]


In [37]:
print(14 * np.ones((3,7)))

[[14. 14. 14. 14. 14. 14. 14.]
 [14. 14. 14. 14. 14. 14. 14.]
 [14. 14. 14. 14. 14. 14. 14.]]


In [38]:
reshape1 = np.arange(40).reshape(5,8)

reshape1

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29, 30, 31],
       [32, 33, 34, 35, 36, 37, 38, 39]])

In [39]:
# Reshape will be similar to the range given to generate the number

# 40 = 5 * 8 or 8 * 5

# 30 = 6 * 5 or 5 * 6

## Random Number Generation

In [40]:
# .seed() means it generate same number on every execution

# it works only in .rand() method

In [41]:
# rand generate int, float 

In [42]:
print(np.random.rand(4))

[0.71188546 0.50784777 0.10480397 0.51396231]


In [43]:
np.random.rand(2,5)

array([[0.82412827, 0.99329014, 0.16742598, 0.11258549, 0.19693901],
       [0.14521665, 0.74339364, 0.95719532, 0.44545455, 0.37586685]])

In [44]:
np.random.rand(5,5)

array([[0.48118861, 0.00574617, 0.52344487, 0.74231322, 0.1320101 ],
       [0.8678696 , 0.39484397, 0.53705358, 0.37562687, 0.82612369],
       [0.99775551, 0.28847976, 0.86718025, 0.34517993, 0.24805062],
       [0.04382657, 0.86929227, 0.10226411, 0.32623655, 0.58730009],
       [0.28743462, 0.32557936, 0.0981543 , 0.12743442, 0.26299309]])

In [45]:
# randn generate positive,negative int,float

In [46]:
np.random.randn(5)

array([ 0.60774759,  1.550798  , -0.37794292, -0.47667942, -1.20864603])

In [47]:
np.random.randn(4,4)

array([[ 8.66762358e-01, -5.57225269e-01, -9.06891432e-01,
        -6.03931886e-01],
       [-6.79356505e-01,  5.52212272e-01,  1.00388746e+00,
        -2.84387319e-01],
       [-1.02920591e+00, -1.91347589e+00, -1.20722050e+00,
         1.11181816e-03],
       [-3.92328020e-01, -1.51708166e+00, -1.63116352e+00,
         8.80932089e-01]])

In [48]:
np.random.randn(5,5)

array([[ 0.87260514, -0.19390567, -0.55577998,  1.27132503, -0.26562248],
       [-0.32713323, -0.28209145, -1.02769546, -1.58583335,  0.75161719],
       [ 0.04850344, -1.88654651, -1.19503441,  0.51025258, -1.02468501],
       [-0.01464013, -0.89421802,  0.49865671, -0.3657798 ,  1.52667689],
       [ 1.64319395,  0.99452636, -0.89905711,  2.50751136, -0.47609608]])

In [49]:
# randint generate complete int number

In [50]:
np.random.randint(5)

3

In [51]:
# last element is the numnber we want to print not a step size

np.random.randint(2,6,3)

array([5, 5, 5])

In [52]:
np.random.randint(1,100,1)

array([61])

In [53]:
np.random.randint(2,100,(5,5))

array([[75, 51, 24, 23, 49],
       [33, 48, 39, 82, 86],
       [22, 81, 75, 74, 70],
       [95, 95, 73, 67, 96],
       [50, 59, 47, 60, 83]])

## A Simple program for generate OTP

In [54]:
import numpy as np

def generate_otp():
    otp1 = np.random.randint(1000,9999,1)
    print("Your otp is: ",otp1)
    
    user_otp = int(input("Enter otp: "))
    if otp1 == user_otp:
        print("Otp matched-- Thanks")
    else:
        print("Wrong Otp")
        
generate_otp()

Your otp is:  [5692]
Enter otp: 5692
Otp matched-- Thanks
