<a href="https://colab.research.google.com/github/ArpanChaudhary/Numpy/blob/main/Numpy2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [113]:
import numpy as np

# **Numpy Condition**

In [114]:
# Generate random number

In [115]:
numbers = np.random.randint(15,70,10)

numbers

array([52, 68, 16, 52, 50, 29, 67, 60, 17, 55])

In [116]:
# Set minimum and maximum numbers according to your choice

In [117]:
np.clip(numbers, a_min=25, a_max=65)

array([52, 65, 25, 52, 50, 29, 65, 60, 25, 55])

In [118]:
# where condition

In [119]:
np.where(numbers < 45)

(array([2, 5, 8]),)

In [120]:
# if we want to see actual data, use index

In [121]:
numbers[[1,5]]

array([68, 29])

# **Reshaping Other ways**

In [122]:
from numpy.random import randint as ri

In [123]:
num = ri(10,90,30)

In [124]:
# reshaping according our way

In [125]:
# here 2 means that there will be 2 matrix of shape(3,5)

num1 = num.reshape(2,3,5)

num1

array([[[69, 54, 11, 73, 16],
        [33, 68, 14, 88, 18],
        [32, 32, 75, 47, 62]],

       [[63, 82, 55, 61, 61],
        [24, 60, 39, 79, 50],
        [24, 71, 14, 78, 43]]])

In [126]:
num2 = num.reshape(5,6)

num2

array([[69, 54, 11, 73, 16, 33],
       [68, 14, 88, 18, 32, 32],
       [75, 47, 62, 63, 82, 55],
       [61, 61, 24, 60, 39, 79],
       [50, 24, 71, 14, 78, 43]])

In [127]:
num3 = num.reshape(6,5)

num3

array([[69, 54, 11, 73, 16],
       [33, 68, 14, 88, 18],
       [32, 32, 75, 47, 62],
       [63, 82, 55, 61, 61],
       [24, 60, 39, 79, 50],
       [24, 71, 14, 78, 43]])

In [128]:
# finding the minimum number in matrix

print("Minimum number in matrix: ", num3.min())

Minimum number in matrix:  11


In [129]:
# finding the maximum number in matrix

print("Maximum number in matrix: ", num3.max())

Maximum number in matrix:  88


In [130]:
# finding average

np.mean(num3)

49.86666666666667

# **Sorting**

In [131]:
num4 = ri(10,100,20).reshape(5,4)

num4

array([[30, 57, 43, 29],
       [51, 63, 30, 43],
       [23, 13, 17, 59],
       [29, 22, 58, 62],
       [73, 64, 97, 61]])

In [132]:
# sorting matrix row_wise
# by default axis =1

np.sort(num4)

array([[29, 30, 43, 57],
       [30, 43, 51, 63],
       [13, 17, 23, 59],
       [22, 29, 58, 62],
       [61, 64, 73, 97]])

In [133]:
# sorting matrix column_wise
# taking axis = 0

np.sort(num4, axis=0)

array([[23, 13, 17, 29],
       [29, 22, 30, 43],
       [30, 57, 43, 59],
       [51, 63, 58, 61],
       [73, 64, 97, 62]])

# **Indexing and Slicing**

In [134]:
arr = np.arange(10,30)

arr

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29])

In [135]:
print("Element at 5 index:",arr[5])

Element at 5 index: 15


In [136]:
print("Element at 10 index:",arr[10])

Element at 10 index: 20


In [137]:
print("Element after 7 index:",arr[7:])

Element after 7 index: [17 18 19 20 21 22 23 24 25 26 27 28 29]


In [138]:
# Indexing from backwards

In [139]:
print(arr)

print(arr[::-1])

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29]
[29 28 27 26 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


In [140]:
# if we want to fetch from backwards by skipping one step

print(arr[::-2])

[29 27 25 23 21 19 17 15 13 11]


In [141]:
# if we want to fetch data from dedicated index, then pass the index number as a list

print("Element at the 2, 4 8 index:",arr[[2,4,8]])

Element at the 2, 4 8 index: [12 14 18]


In [142]:
# slicing the data

sliced_data = arr[1:5]

sliced_data

array([11, 12, 13, 14])

In [143]:
# Matrix

In [144]:
my_mat = [[1,2,3],[4,5,6],[7,8,9]]

my_mat = np.array(my_mat)

my_mat

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [145]:
# for indexing in the matrix

# matrix_name[][]

# in first square braces is taken as row,
# then in second braces is for element_index we want to fetch

# matrix_name[,][]

# first square braces taken as [row,column]
# second square braces taken as [element_index]

In [146]:
print("Entire row at index 2:", my_mat[2])

Entire row at index 2: [7 8 9]


In [147]:
print("Entire column at index 2:", my_mat[:,2])

Entire column at index 2: [3 6 9]


In [148]:
print("Entire column after index 1:", my_mat[:,1:])

Entire column after index 1: [[2 3]
 [5 6]
 [8 9]]


In [149]:
print(my_mat[1:2,1:2])

[[5]]


In [150]:
print(my_mat[0:2,[1,2]])

[[2 3]
 [5 6]]


## Updating Matrix

In [151]:
print("Original Matrix:\n", my_mat)

Original Matrix:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]


In [152]:
my_mat[0,1] = 2
my_mat[1,0] = 40

my_mat

array([[ 1,  2,  3],
       [40,  5,  6],
       [ 7,  8,  9]])

In [153]:
my_mat[2,0] = 70
my_mat[2,2] = 90

my_mat

array([[ 1,  2,  3],
       [40,  5,  6],
       [70,  8, 90]])

## Subseting

In [154]:
mat = np.array(ri(10,90,15)).reshape(3,5)

mat

array([[84, 16, 17, 70, 43],
       [32, 24, 77, 21, 36],
       [25, 23, 25, 12, 74]])

In [155]:
mat>50

array([[ True, False, False,  True, False],
       [False, False,  True, False, False],
       [False, False, False, False,  True]])

In [156]:
mat[mat>50]

array([84, 70, 77, 74])

In [157]:
print(np.where(mat == 10))

(array([], dtype=int64), array([], dtype=int64))


In [158]:
print(np.where(mat > 40))

(array([0, 0, 0, 1, 2]), array([0, 3, 4, 2, 4]))


In [159]:
# If want to return number into some text from matrix

age = 60

np.where(mat > age, "Retired", "Working")

array([['Retired', 'Working', 'Working', 'Retired', 'Working'],
       ['Working', 'Working', 'Retired', 'Working', 'Working'],
       ['Working', 'Working', 'Working', 'Working', 'Retired']],
      dtype='<U7')

## Universal Function

In [160]:
mat1 = np.array(ri(1,10,9)).reshape(3,3)

mat2 = np.array(ri(1,10,9)).reshape(3,3)

print(mat1)
print("**********")
print(mat2)

[[6 3 1]
 [1 6 7]
 [3 9 6]]
**********
[[4 3 7]
 [6 8 6]
 [5 7 1]]


In [161]:
print(mat1 + mat2)

[[10  6  8]
 [ 7 14 13]
 [ 8 16  7]]


In [162]:
print(mat1 * mat2)

[[24  9  7]
 [ 6 48 42]
 [15 63  6]]


## Broadcasting

In [163]:
start = np.zeros((3,3))

start

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [164]:
add_rows = np.array([[1,0,2]])

print(add_rows)

[[1 0 2]]


In [165]:
y = add_rows + start

y

array([[1., 0., 2.],
       [1., 0., 2.],
       [1., 0., 2.]])

In [166]:
new_row = add_rows.T
new_row

array([[1],
       [0],
       [2]])

In [167]:
z = new_row + start

z

array([[1., 1., 1.],
       [0., 0., 0.],
       [2., 2., 2.]])

## Array Math

In [168]:
print(mat1)
print("***********")
print(mat2)

[[6 3 1]
 [1 6 7]
 [3 9 6]]
***********
[[4 3 7]
 [6 8 6]
 [5 7 1]]


In [169]:
np.sqrt(mat1)

array([[2.44948974, 1.73205081, 1.        ],
       [1.        , 2.44948974, 2.64575131],
       [1.73205081, 3.        , 2.44948974]])

In [170]:
np.square(mat2)

array([[16,  9, 49],
       [36, 64, 36],
       [25, 49,  1]])

## Similarly other functions can be applied to matrix